# Generated by Django 6.0.1 on 2026-01-27 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedbackmodel_delete_tumorprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='MedicalChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistrationmodel')),
            ],
            options={
                'db_table': 'MedicalChatHistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_image', models.ImageField(upload_to='nutrition_uploads/')),
                ('analysis_result', models.TextField()),
                ('health_percentage', models.IntegerField(blank=True, null=True)),
                ('calories_info', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistrationmodel')),
            ],
            options={
                'db_table': 'NutritionAnalysisHistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('medical', 'Medical Advice'), ('nutrition', 'Nutrition'), ('lifestyle', 'Lifestyle'), ('exercise', 'Exercise')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistrationmodel')),
            ],
            options={
                'db_table': 'PersonalizedRecommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
