# Generated by Django 6.0.1 on 2026-01-27 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userregistrationmodel_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_health_score', models.IntegerField(default=50)),
                ('total_queries', models.IntegerField(default=0)),
                ('total_nutrition_analyses', models.IntegerField(default=0)),
                ('avg_nutrition_score', models.IntegerField(default=0)),
                ('top_health_concerns', models.TextField(default='')),
                ('activity_streak', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_insight', to='users.userregistrationmodel')),
            ],
            options={
                'db_table': 'HealthInsights',
            },
        ),
    ]
