# Generated by Django 6.0.1 on 2026-01-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_healthinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_conditions', models.TextField(default='{}')),
                ('allergies', models.TextField(default='[]')),
                ('medications', models.TextField(default='[]')),
                ('dietary_restrictions', models.TextField(default='[]')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='users.userregistrationmodel')),
            ],
            options={
                'db_table': 'UserHealthProfiles',
            },
        ),
    ]
