# Generated by Django 6.0.1 on 2026-01-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userhealthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback_type',
            field=models.CharField(choices=[('medical', 'Medical Bot'), ('nutrition', 'Nutrition Bot'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
